var items = [
    { text: 'Manopla', dado: '1D6', distacia: 0, descripcion: '', peso: 0, costo: 0 },
    { text: 'Navaja', dado: '1D6', distacia: 0, descripcion: '', peso: 0, costo: 0 },
    { text: 'Botella', dado: '1D6', distacia: 0, descripcion: '', peso: 0, costo: 0 },
    { text: 'Palanca', dado: '2D6', distacia: 0, descripcion: '', peso: 0, costo: 0 },
    { text: 'Barra', dado: '2D6', distacia: 0, descripcion: '', peso: 0, costo: 0 },
    { text: 'Hacha pequena', dado: '2D6', distacia: 0, descripcion: '', peso: 0, costo: 0 },
    { text: 'Cuchillo de carnicero', dado: '3D6', distacia: 0, descripcion: '', peso: 0, costo: 0 },
    { text: 'Bate', dado: '3D6', distacia: 0, descripcion: '', peso: 0, costo: 0 },
    { text: 'Extintor', dado: '3D6', distacia: 0, descripcion: '', peso: 0, costo: 0 },
    { text: 'Hacha de mano', dado: '3D6', distacia: 0, descripcion: '', peso: 0, costo: 0 },
    { text: 'Motosierra', dado: '4D6', distacia: 0, descripcion: '', peso: 0, costo: 0 },
    { text: 'Arma calibre 22', dado: '1D6', distacia: 10, descripcion: '', peso: 0, costo: 0 },
    { text: 'Arma calibre 38', dado: '2D6', distacia: 10, descripcion: '', peso: 0, costo: 0 },
    { text: 'Arma calibre 45', dado: '3D6', distacia: 10, descripcion: '', peso: 0, costo: 0 },
    { text: 'Subfusil calibre 5.56', dado: '2D6', distacia: 15, descripcion: '', peso: 0, costo: 0 },
    { text: 'Subfusil calibre 7.62', dado: '3D6', distacia: 15, descripcion: '', peso: 0, costo: 0 },
    { text: 'Rifle calibre 22', dado: '2D6', distacia: 30, descripcion: '', peso: 0, costo: 0 },
    { text: 'Rifle calibre 303', dado: '3D6', distacia: 30, descripcion: '', peso: 0, costo: 0 },
    { text: 'Rifle calibre 45', dado: '4D6', distacia: 30, descripcion: '', peso: 0, costo: 0 },
    { text: 'Escopeta 9 mm', dado: '3D6', distacia: 10, descripcion: '', peso: 0, costo: 0 },
    { text: 'Escopeta 12 mm', dado: '4D6', distacia: 10, descripcion: '', peso: 0, costo: 0 },
    { text: 'Ametralladora', dado: '3D6', distacia: 30, descripcion: '', peso: 0, costo: 0 },
    { text: 'Municion Arma', dado: '', distacia: 0, descripcion: '', peso: 0, costo: 0 },
    { text: 'Municion Subfusil', dado: '', distacia: 0, descripcion: '', peso: 0, costo: 0 },
    { text: 'Municion Rifle', dado: '', distacia: 0, descripcion: '', peso: 0, costo: 0 },
    { text: 'Municion Ametralladora', dado: '', distacia: 0, descripcion: '', peso: 0, costo: 0 },
    { text: 'Municion Escopeta', dado: '', distacia: 0, descripcion: '', peso: 0, costo: 0 },
];